
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yfkmrulfxbfkjfwhqxgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlma21ydWxmeGJma2pmd2hxeGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODg4MTksImV4cCI6MjA2MTA2NDgxOX0.ow78h9_C7pqf0BqnNczG9fDBo09bhpRLimc64ttwhHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
